server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /home/jean/Documents/microservices-repo

#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: http
#        native:
#          search-paths: fornecedor
